//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("HaveyouseenmeModel", "product_id_fk", "product", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MyMVCLatest.product), "sale", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyMVCLatest.sale), true)]

#endregion

namespace MyMVCLatest
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HaveyouseenmeEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HaveyouseenmeEntities object using the connection string found in the 'HaveyouseenmeEntities' section of the application configuration file.
        /// </summary>
        public HaveyouseenmeEntities() : base("name=HaveyouseenmeEntities", "HaveyouseenmeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HaveyouseenmeEntities object.
        /// </summary>
        public HaveyouseenmeEntities(string connectionString) : base(connectionString, "HaveyouseenmeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HaveyouseenmeEntities object.
        /// </summary>
        public HaveyouseenmeEntities(EntityConnection connection) : base(connection, "HaveyouseenmeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PetType> PetTypes
        {
            get
            {
                if ((_PetTypes == null))
                {
                    _PetTypes = base.CreateObjectSet<PetType>("PetTypes");
                }
                return _PetTypes;
            }
        }
        private ObjectSet<PetType> _PetTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<product> products
        {
            get
            {
                if ((_products == null))
                {
                    _products = base.CreateObjectSet<product>("products");
                }
                return _products;
            }
        }
        private ObjectSet<product> _products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sale> sales
        {
            get
            {
                if ((_sales == null))
                {
                    _sales = base.CreateObjectSet<sale>("sales");
                }
                return _sales;
            }
        }
        private ObjectSet<sale> _sales;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Setting> Settings
        {
            get
            {
                if ((_Settings == null))
                {
                    _Settings = base.CreateObjectSet<Setting>("Settings");
                }
                return _Settings;
            }
        }
        private ObjectSet<Setting> _Settings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Status> Status
        {
            get
            {
                if ((_Status == null))
                {
                    _Status = base.CreateObjectSet<Status>("Status");
                }
                return _Status;
            }
        }
        private ObjectSet<Status> _Status;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tab1> tab1
        {
            get
            {
                if ((_tab1 == null))
                {
                    _tab1 = base.CreateObjectSet<tab1>("tab1");
                }
                return _tab1;
            }
        }
        private ObjectSet<tab1> _tab1;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblemployee> tblemployees
        {
            get
            {
                if ((_tblemployees == null))
                {
                    _tblemployees = base.CreateObjectSet<tblemployee>("tblemployees");
                }
                return _tblemployees;
            }
        }
        private ObjectSet<tblemployee> _tblemployees;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PetTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPetTypes(PetType petType)
        {
            base.AddObject("PetTypes", petType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToproducts(product product)
        {
            base.AddObject("products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sales EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosales(sale sale)
        {
            base.AddObject("sales", sale);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Settings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSettings(Setting setting)
        {
            base.AddObject("Settings", setting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Status EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStatus(Status status)
        {
            base.AddObject("Status", status);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tab1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotab1(tab1 tab1)
        {
            base.AddObject("tab1", tab1);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblemployees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblemployees(tblemployee tblemployee)
        {
            base.AddObject("tblemployees", tblemployee);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HaveyouseenmeModel", Name="PetType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PetType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PetType object.
        /// </summary>
        /// <param name="petTypeID">Initial value of the PetTypeID property.</param>
        public static PetType CreatePetType(global::System.Int32 petTypeID)
        {
            PetType petType = new PetType();
            petType.PetTypeID = petTypeID;
            return petType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PetTypeID
        {
            get
            {
                return _PetTypeID;
            }
            set
            {
                if (_PetTypeID != value)
                {
                    OnPetTypeIDChanging(value);
                    ReportPropertyChanging("PetTypeID");
                    _PetTypeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PetTypeID");
                    OnPetTypeIDChanged();
                }
            }
        }
        private global::System.Int32 _PetTypeID;
        partial void OnPetTypeIDChanging(global::System.Int32 value);
        partial void OnPetTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PetTypeDescription
        {
            get
            {
                return _PetTypeDescription;
            }
            set
            {
                OnPetTypeDescriptionChanging(value);
                ReportPropertyChanging("PetTypeDescription");
                _PetTypeDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PetTypeDescription");
                OnPetTypeDescriptionChanged();
            }
        }
        private global::System.String _PetTypeDescription;
        partial void OnPetTypeDescriptionChanging(global::System.String value);
        partial void OnPetTypeDescriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HaveyouseenmeModel", Name="product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new product object.
        /// </summary>
        /// <param name="productid">Initial value of the productid property.</param>
        public static product Createproduct(global::System.Int32 productid)
        {
            product product = new product();
            product.productid = productid;
            return product;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 productid
        {
            get
            {
                return _productid;
            }
            set
            {
                if (_productid != value)
                {
                    OnproductidChanging(value);
                    ReportPropertyChanging("productid");
                    _productid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("productid");
                    OnproductidChanged();
                }
            }
        }
        private global::System.Int32 _productid;
        partial void OnproductidChanging(global::System.Int32 value);
        partial void OnproductidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String product1
        {
            get
            {
                return _product1;
            }
            set
            {
                Onproduct1Changing(value);
                ReportPropertyChanging("product1");
                _product1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product1");
                Onproduct1Changed();
            }
        }
        private global::System.String _product1;
        partial void Onproduct1Changing(global::System.String value);
        partial void Onproduct1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> cost
        {
            get
            {
                return _cost;
            }
            set
            {
                OncostChanging(value);
                ReportPropertyChanging("cost");
                _cost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cost");
                OncostChanged();
            }
        }
        private Nullable<global::System.Decimal> _cost;
        partial void OncostChanging(Nullable<global::System.Decimal> value);
        partial void OncostChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HaveyouseenmeModel", "product_id_fk", "sale")]
        public EntityCollection<sale> sales
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<sale>("HaveyouseenmeModel.product_id_fk", "sale");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<sale>("HaveyouseenmeModel.product_id_fk", "sale", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HaveyouseenmeModel", Name="sale")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sale : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sale object.
        /// </summary>
        /// <param name="saleid">Initial value of the saleid property.</param>
        /// <param name="saledate">Initial value of the saledate property.</param>
        public static sale Createsale(global::System.Int32 saleid, global::System.DateTime saledate)
        {
            sale sale = new sale();
            sale.saleid = saleid;
            sale.saledate = saledate;
            return sale;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 saleid
        {
            get
            {
                return _saleid;
            }
            set
            {
                if (_saleid != value)
                {
                    OnsaleidChanging(value);
                    ReportPropertyChanging("saleid");
                    _saleid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("saleid");
                    OnsaleidChanged();
                }
            }
        }
        private global::System.Int32 _saleid;
        partial void OnsaleidChanging(global::System.Int32 value);
        partial void OnsaleidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime saledate
        {
            get
            {
                return _saledate;
            }
            set
            {
                OnsaledateChanging(value);
                ReportPropertyChanging("saledate");
                _saledate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("saledate");
                OnsaledateChanged();
            }
        }
        private global::System.DateTime _saledate;
        partial void OnsaledateChanging(global::System.DateTime value);
        partial void OnsaledateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> quantity
        {
            get
            {
                return _quantity;
            }
            set
            {
                OnquantityChanging(value);
                ReportPropertyChanging("quantity");
                _quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("quantity");
                OnquantityChanged();
            }
        }
        private Nullable<global::System.Int32> _quantity;
        partial void OnquantityChanging(Nullable<global::System.Int32> value);
        partial void OnquantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> productid
        {
            get
            {
                return _productid;
            }
            set
            {
                OnproductidChanging(value);
                ReportPropertyChanging("productid");
                _productid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("productid");
                OnproductidChanged();
            }
        }
        private Nullable<global::System.Int32> _productid;
        partial void OnproductidChanging(Nullable<global::System.Int32> value);
        partial void OnproductidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HaveyouseenmeModel", "product_id_fk", "product")]
        public product product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<product>("HaveyouseenmeModel.product_id_fk", "product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<product>("HaveyouseenmeModel.product_id_fk", "product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<product> productReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<product>("HaveyouseenmeModel.product_id_fk", "product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<product>("HaveyouseenmeModel.product_id_fk", "product", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HaveyouseenmeModel", Name="Setting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Setting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Setting object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="key">Initial value of the Key property.</param>
        public static Setting CreateSetting(global::System.Int32 id, global::System.String key)
        {
            Setting setting = new Setting();
            setting.Id = id;
            setting.Key = key;
            return setting;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Key
        {
            get
            {
                return _Key;
            }
            set
            {
                OnKeyChanging(value);
                ReportPropertyChanging("Key");
                _Key = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Key");
                OnKeyChanged();
            }
        }
        private global::System.String _Key;
        partial void OnKeyChanging(global::System.String value);
        partial void OnKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HaveyouseenmeModel", Name="Status")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Status : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Status object.
        /// </summary>
        /// <param name="statusID">Initial value of the StatusID property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static Status CreateStatus(global::System.Int32 statusID, global::System.String description)
        {
            Status status = new Status();
            status.StatusID = statusID;
            status.Description = description;
            return status;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StatusID
        {
            get
            {
                return _StatusID;
            }
            set
            {
                if (_StatusID != value)
                {
                    OnStatusIDChanging(value);
                    ReportPropertyChanging("StatusID");
                    _StatusID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StatusID");
                    OnStatusIDChanged();
                }
            }
        }
        private global::System.Int32 _StatusID;
        partial void OnStatusIDChanging(global::System.Int32 value);
        partial void OnStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HaveyouseenmeModel", Name="tab1")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tab1 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tab1 object.
        /// </summary>
        /// <param name="id1">Initial value of the id1 property.</param>
        public static tab1 Createtab1(global::System.Int32 id1)
        {
            tab1 tab1 = new tab1();
            tab1.id1 = id1;
            return tab1;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id1
        {
            get
            {
                return _id1;
            }
            set
            {
                if (_id1 != value)
                {
                    Onid1Changing(value);
                    ReportPropertyChanging("id1");
                    _id1 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id1");
                    Onid1Changed();
                }
            }
        }
        private global::System.Int32 _id1;
        partial void Onid1Changing(global::System.Int32 value);
        partial void Onid1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HaveyouseenmeModel", Name="tblemployee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblemployee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblemployee object.
        /// </summary>
        /// <param name="employeeid">Initial value of the employeeid property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="gender">Initial value of the gender property.</param>
        /// <param name="city">Initial value of the city property.</param>
        public static tblemployee Createtblemployee(global::System.Int32 employeeid, global::System.String name, global::System.String gender, global::System.String city)
        {
            tblemployee tblemployee = new tblemployee();
            tblemployee.employeeid = employeeid;
            tblemployee.name = name;
            tblemployee.gender = gender;
            tblemployee.city = city;
            return tblemployee;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 employeeid
        {
            get
            {
                return _employeeid;
            }
            set
            {
                if (_employeeid != value)
                {
                    OnemployeeidChanging(value);
                    ReportPropertyChanging("employeeid");
                    _employeeid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("employeeid");
                    OnemployeeidChanged();
                }
            }
        }
        private global::System.Int32 _employeeid;
        partial void OnemployeeidChanging(global::System.Int32 value);
        partial void OnemployeeidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                if (_name != value)
                {
                    OnnameChanging(value);
                    ReportPropertyChanging("name");
                    _name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("name");
                    OnnameChanged();
                }
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gender
        {
            get
            {
                return _gender;
            }
            set
            {
                if (_gender != value)
                {
                    OngenderChanging(value);
                    ReportPropertyChanging("gender");
                    _gender = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("gender");
                    OngenderChanged();
                }
            }
        }
        private global::System.String _gender;
        partial void OngenderChanging(global::System.String value);
        partial void OngenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                if (_city != value)
                {
                    OncityChanging(value);
                    ReportPropertyChanging("city");
                    _city = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("city");
                    OncityChanged();
                }
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> deptid
        {
            get
            {
                return _deptid;
            }
            set
            {
                OndeptidChanging(value);
                ReportPropertyChanging("deptid");
                _deptid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("deptid");
                OndeptidChanged();
            }
        }
        private Nullable<global::System.Int32> _deptid;
        partial void OndeptidChanging(Nullable<global::System.Int32> value);
        partial void OndeptidChanged();

        #endregion

    
    }

    #endregion

    
}
